services:
    srkits.razor_pay_plugin.form.type.gateway_configuration:
        class: Srkits\SyliusRazorPayPlugin\Form\Type\RazorpayGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: razorpay, label: Razor Pay }
            - { name: form.type }

    srkits.razor_pay_plugin.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Srkits\SyliusRazorPayPlugin\RazorpayGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: razorpay }

    srkits.razor_pay_plugin.bridge.razorpay:
        class: Srkits\SyliusRazorPayPlugin\Bridge\RazorpayBridge

    srkits.razor_pay_plugin.razorpay_action:
        class: Srkits\SyliusRazorPayPlugin\Action\RazorpayAction
        public: true
        arguments: ['@srkits.razor_pay_plugin.bridge.razorpay', '@payum']
        tags:
            - { name: payum.action, factory: razorpay, alias: payum.action.set_razorpay }
